# Generated by Django 4.1 on 2022-08-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_beverage_dankness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='dankness',
            field=models.CharField(max_length=50),
        ),
    ]
