# Generated by Django 4.1 on 2022-08-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_beverage_dankness'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='beverages',
            field=models.ManyToManyField(to='main_app.beverage'),
        ),
    ]
